firm:
  layout:       'layout'
  sass_dir:     'trst/assets/stylesheets/asrv'
  css_dir:      'public/stylesheets/asrv'
  images_dir:   'public/images/asrv'
  css_path:     '/stylesheets/asrv'
  images_path:  '/images/asrv'
  i18n_path:    'trst'
  head_title:   'TrustSys'
  header_text:  'TrustSys AutoSrv'
  footer_text:  '&copy; 2005-2012 kfl62'
  footer_title: 'Ferenc-Loránt Kiss'
  db_devel:     'demo_asrv'
  db_test:      'demo_test'
  db_prod:      'demo_asrv'
