firm:
  public:
    controller: 'public'
    views:      'clns'
    layout:     'clns'
    page:
      title:        'Cleaning Ltd.'
      header:       'CLNS motto'
      footer_text:  '&copy; 2005-2012 Cleaning Ltd.'
      footer_title: 'Ferenc-Loránt Kiss'
  system:
    page:
      title:        'TrustSys - Clns'
      header:       'TrustSys Clns'
      footer_text:  '&copy; 2005-2012 kfl62'
      footer_title: 'Ferenc-Loránt Kiss'

  sass_dir:     'system/assets/stylesheets/clns'
  css_dir:      'public/stylesheets/clns'
  images_dir:   'public/images/clns'
  css_path:     '/stylesheets/clns'
  images_path:  '/images/clns'
  i18n_path:    'clns'
  js_path:      'clns'

  models_path:  [trst, clns]
  db_devel:     'trst_clns'
  db_test:      'trst_test'
  db_prod:      'trst_clns'
